### ISSUE TITLE
image shrinking in what is semikolan section

### ISSUE THREAD

**Issue by satyamsharma17** [semikolan-co/semikolan-react#118]
**Describe the bug**
Image in What is Semikolan? section is shrinking in full web view but responsive in mobile view that is less than 1150 px and shrinking before 1150 px.

**To Reproduce**
1. Go to semikolan.co website.
2. Scroll down to What is Semikolan? section.
4. See image shrink error.

**Expected behavior**
Square size and responsiveness of that particular image in all views.

**Screenshots**
![Screenshot (113)](https://user-images.githubusercontent.com/72562562/192972361-199226df-4ccc-4428-8e99-4d32d3b3ae32.png)
![Screenshot (114)](https://user-images.githubusercontent.com/72562562/192972380-50322ec9-3967-46ff-a17d-2087053f9072.png)

**Comment by najeebkp** [comment]
Hi @satyamsharma17 @ankurg132 can you please assign this to me. I'll take care.

**Comment by ankurg132** [comment]
Go for it @najeebkp! 🚀
