### ISSUE TITLE
Open a new tab on clicking Read More in Hacktoberfest Page

### ISSUE THREAD

**Issue by ankurg132** [semikolan-co/semikolan-react#138]
**Describe the bug**
The Hacktoberfest page should open a new tab on clicking Read More in the projects repository section.

**To Reproduce**
1. Go to https://semikolan.co/hacktoberfest
2. Scroll down to 'Projects repository' section
3. Click on the 'Read More' button

**Expected behavior**
This should open up on a new tab, a simple change in the html code should just do the work!

**Comment by S-Parker7000** [comment]
I am on it

**Comment by Abhishek-Vaidya** [comment]
I can solve your issue can you assign me this issue?

**Comment by ankurg132** [comment]
Since @S-Parker7000 is the first, assigning to issue to you. Good luck!
