### ISSUE TITLE
Add Hacktoberfest Projects

### ISSUE THREAD

**Issue by satyamsharma17** [semikolan-co/semikolan-react#146]
**Describe the bug**
Add New Hacktoberfest Projects on the Hacktoberfest Page.

**To Reproduce**
1. Go to 'semikolan.co/hacktoberfest'
2. Go to 'Projects Repository Section'
3. Scroll down to end of the section.
4. Add new projects here.

**Expected Behavior**
New Projects for Hacktoberfest should be visible with their particular repository link.

**Comment by MAnishSingh13275** [comment]
PLEASE ASSIGN THIS ISSUE TO ME.

**Comment by Akshat325FLG** [comment]
I can do this please assign this to me.

**Comment by ankurg132** [comment]
Hey @satyamsharma17 @MAnishSingh13275, there are still a lot of repositories pending to be added in the main website. Can you update the projects as soon as possible.

**Comment by satyamsharma17** [comment]
Okay sir we'll do as soon as possible!
