### ISSUE TITLE
add search functionality in leaderboard

### ISSUE THREAD

**Issue by RajatBhaskare7** [semikolan-co/semikolan-react#148]
add the search filter functionality in the search for searching username in it (note: user can search both in upercase and lowercase)

**Comment by SamalaSumanth0262** [comment]
Assign this to me

**Comment by SamalaSumanth0262** [comment]
> add the search filter functionality in the search for searching username in it (note: user can search both in upercase and lowercase)

Can I work on this please ?

**Comment by SamalaSumanth0262** [comment]
https://github.com/semikolan-co/semikolan-react/pull/169 please find the PR for this feature

**Comment by SamalaSumanth0262** [comment]
@RajatBhaskare7 @ankurg132

**Comment by ankurg132** [comment]
This is amazing @SamalaSumanth0262! Congrats on making your PR!
