### ISSUE TITLE
Add navigation in Hacktoberfest page

### ISSUE THREAD

**Issue by ankurg132** [semikolan-co/semikolan-react#161]
We have the leaderboard page at https://semikolan.co/hacktoberfest/leaderboard, we should include the link to this page at the Hacktoberfest page https://semikolan.co/hacktoberfest. This link can be in the form of a button addition somewhere that fits with the UI and easier for a user to navigate.

**Comment by ashishkashyap31** [comment]
Can I work on this?

**Comment by ankurg132** [comment]
One issue at a time @ashishkashyap31!

**Comment by ashishkashyap31** [comment]
ok @ankurg132

**Comment by ekiira** [comment]
Hello, I would like to work on this
Can you assign it to me?

**Comment by SubinDuresh** [comment]
Hi @ankurg132 I am interested in working on this, can you assign it to me?

**Comment by ankurg132** [comment]
Hey @ekiira, go for it!

**Comment by ekiira** [comment]
Hi @ankurg132 
This issue has been done in #168.

**Comment by ankurg132** [comment]
Closed the issue! You can check out some other issues to work on!
