### ISSUE TITLE
Add navigation to Hacktoberfest Page from Homepage

### ISSUE THREAD

**Issue by ankurg132** [semikolan-co/semikolan-react#162]
We have the Hacktoberfest page at https://semikolan.co/hacktoberfest/, we should include the link to this page at the Homepage https://semikolan.co/. This link can be in the form of a button addition somewhere that fits with the UI and easier for a user to navigate.

**Comment by ashishkashyap31** [comment]
can i work on this?

**Comment by ankurg132** [comment]
Sure @ashishkashyap31, go for it!
