### ISSUE TITLE
Add an about semikolan section in readme.md

### ISSUE THREAD

**Issue by ankurg132** [semikolan-co/semikolan-react#35]
Since this is the main website of Semikolan, we should add an about Semikolan section in the readme of this repository (it can be the same as About us description in the website) and a link to discord.semikolan.co to join the community and for further discussions related to Semikolan projects.

**Comment by kiran-thilak** [comment]
@ankurg132 Can i work on this ?

**Comment by meinhoonharsh** [comment]
@kiran-thilak Assigned Issue to you

**Comment by kiran-thilak** [comment]
Could you please review the Pull Request.
