### ISSUE TITLE
Change footer link from semikolan-dev to semikolan-co

### ISSUE THREAD

**Issue by ankurg132** [semikolan-co/semikolan-react#39]
Currently the link in footer targets to https://github.com/semikolan-dev, however we have now changed it to https://github.com/semikolan-co and hence the footer link should be changed too.

**Comment by neodark** [comment]
Can you assign me this one please ?

**Comment by neodark** [comment]
Should all the files (src/semikolan.json, src/component/Footer.js, src/component/Work.js) be changed or only the Footer file ?

**Comment by ankurg132** [comment]
Sure, go ahead!

**Comment by ankurg132** [comment]
Wherever github.com/semikolan-dev is mentioned, you can change all the link to github.com/semikolan-co.

**Comment by neodark** [comment]
Done. Thanks a lot!
