### ISSUE TITLE
Navigation and contact form not showing in Contact Page

### ISSUE THREAD

**Issue by ankurg132** [semikolan-co/semikolan-react#69]
**Describe the bug**
Navigation and contact form not showing in Contact Page

**To Reproduce**
1. Go to semikolan.co/contact

**Expected behavior**
There should be a navigation bar, footer and contact form on the page.

**Screenshots**
![image](https://user-images.githubusercontent.com/31045221/139803535-b0d2e6b1-e224-4cd8-bc9c-b3e37fcd2bc8.png)
I'm only seeing this much currently.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Opera

**Comment by wilsonfurtado2000** [comment]
assign this to me

**Comment by meinhoonharsh** [comment]
Closing this Issue, because it's fixed
