### ISSUE TITLE
Email id in subscribe form not going to backend

### ISSUE THREAD

**Issue by ankurg132** [semikolan-co/semikolan-react#75]
**Describe the bug**
Once we subscribe to the newsletter the email id registered is not going to the backend, and instead we are getting a None response in the backend.

**To Reproduce**
1. Go to 'https://semikolan.co#footer' , add your email ID.
2. Verify the captcha and subscribe.
3. You won't get any confirmation email and verified via backend too that we're getting "None" as the email.

**Comment by sauravrajleaf** [comment]
Please this assign it to me.

**Comment by ankurg132** [comment]
Go for it @sauravrajleaf

**Comment by sauravrajleaf** [comment]
I have a doubt regarding which back-end service has to be used for enabling the subscription feature? And also, should i use some online email service where all the emails gets stored or should i use Node.js & some database for storing the emails?

**Comment by ankurg132** [comment]
Hey, the backend is hosted on Replit.com for now which is using the Sendinblue SDK to send emails. Anyways, @meinhoonharsh has recently worked on this issue and it's fixed now. Closing this issue, you can check out many more active issues or create a new one. You can also join our Discord https://discord.semikolan.co to check out all the projects.

**Comment by sauravrajleaf** [comment]
Okay. Thanks for the information.
